### ISSUE TITLE
Make paths of child elements independent of parent elements where possible

### ISSUE THREAD

**Issue by huugouwersloot** [open-imx/imxIcons#29]
Not all systems store the entire path including parent elements, which makes it tougher to call the right icon in the current structure.

A possible fix could be to be able to call for example "ReflectorPost" as well as "Signal.ReflectorPost" and "StopMarkerBoard.ReflectorPost". If the symbol changes depending on the parent objecttype, the most common version could be used as default.

**Comment by Hazedd** [comment]
sound like a good idea, placed on backlog
