### ISSUE TITLE
Implement optional_properties

### ISSUE THREAD

**Issue by Woestebanaan** [open-imx/imxIcons#49]
Hi,

The Icon API as an option to add optional_properties. This is weird because in essence all properties are optional.

Best regards,
Woeste

**Comment by Hazedd** [comment]
Hi Woeste,

Thank you for your feedback!

You bring up an excellent point. The `optional_properties` field was introduced to define non-native IMX properties, such as "trackside" (spoorzijde), which can be used to set specific behaviors like the direction of an arrow on a sign.

That said, I understand that the current name might be confusing, as all properties are inherently optional. To address this, we are considering the following options:

- Renaming `optional_properties` to a more descriptive term (e.g., `non_native_properties` or `custom_properties`).
- Temporarily removing this feature until its intended functionality is fully supported.

We’d love to hear your thoughts or if you have a preference for how we proceed.

Best regards,

**Comment by Woestebanaan** [comment]
I agree, it would be nice to have an option to mirror the svgs in case the TrackSide is important. But you can argue that this is seperate from the mapping. Its just an visualisation option.

**Comment by Hazedd** [comment]
Simply mirroring will not address all cases. For instance, we have the letter 'P' on permissive signals; if we mirror that, it no longer resembles a 'P'. Another example is the spreader lens: when we mirror that icon, it results in a distorted appearance.
